name: Lint & formatting

on:
    push:
        tags:
            - "*"

defaults:
  run:
    working-directory: ./admin-panel


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: any
          flutter-version-file: admin-panel/pubspec.yaml

      - run: flutter --version
    
      - uses: microsoft/setup-msstore-cli@v1

      - name: Configure the Microsoft Store CLI
        env:
          tenantId: ${{ secrets.tenantId }}
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{ secrets.clientSecret }}
          sellerId: ${{ secrets.sellerId }}
        run: msstore reconfigure --tenantId $tenantId --clientId $clientId --clientSecret $clientSecret--sellerId $sellerId
    
      - name: Install dependencies
        run: flutter pub get

      - name: generate files
        run: dart run build_runner build --delete-conflicting-outputs
        
      - name: Create MSIX package
        run: msstore package .
        
      - name: Publish MSIX to the Microsoft Store
        run: msstore publish -v
     
